name: Firebase Secret
on:
  workflow_dispatch:
    inputs:
      env-name:
        type: choice
        description: 'select env name'
        required: true
        options: 
        - prod
        - test
jobs:
  Set-Secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Secret script
        env:
          FILE_NAME: ${{ github.event.inputs.env-name }}
        run: |
          chmod +x ./secret_action.sh
          bash secret_action.sh
