name: Firebase Secret
on:
  workflow_dispatch:
    inputs:
      env-name:
        description: 'Enter env name'
        required: true
        default: 'test'
jobs:
  Set-Secrets:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Run Secret script
        run: |
          pwd
          ls -al
          chmod +x "${GITHUB_WORKSPACE}/.github/secret_action.sh"
          "${GITHUB_WORKSPACE}/.github/secret_action.sh ${inputs.env-name}"
