name: Firebase Secret
on:
  workflow_dispatch:
    inputs:
      env-name:
        type: choice
        description: 'select env name'
        required: true
        options: 
        - production
        - test
jobs:
  Set-Secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Firebase Login
        uses: w9jds/firebase-action@master
        with:
          args: use test
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - uses: actions/checkout@v2
      - name: Run Secret script
        env:
          FILE_NAME: ${{ github.event.inputs.env-name }}
        run: |
          chmod +x ./secret_action.sh
          bash secret_action.sh
